#! /bin/bash

BASH_ENV=$1

NUMBER=$(( RANDOM % 4 + 1 ));
UNT_USRNM="UNITY_USERNAME${NUMBER}";
UNT_PSSWRD="UNITY_PASSWORD${NUMBER}";
UNT_SRL="UNITY_SERIAL${NUMBER}";
echo "export UNITY_USERNAME=${!UNT_USRNM}" >> $BASH_ENV
echo "export UNITY_PASSWORD=${!UNT_PSSWRD}" >> $BASH_ENV
echo "export UNITY_SERIAL=${!UNT_SRL}" >> $BASH_ENV