# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)

lane :publish_to_firebase do |options|
  
  firebase_app_distribution(
     app: "#{options[:app_id]}",
     groups: "internal",
     release_notes_file: "release-note.txt",
     apk_path: "#{options[:artifact_name]}",
     firebase_cli_token: "#{options[:firebase_token]}"
  )
end
